data was instantiated in a conditional causing fetches that only tried to get ESS data to fail with:
UnboundLocalError: cannot access local variable 'data' where it is not associated with a value